#!/usr/bin/env python3
"""
stickers/ と icons/ フォルダの中身を自動でスキャンして、
docs/index.html にギャラリーページを生成するスクリプト。

使い方:
- 画像を stickers/ か icons/ に追加して push するだけ。
- GitHub Actions (.github/workflows/build-gallery.yml) が
  このスクリプトを自動実行し、ギャラリーを更新してくれる。
- 手動で実行したい場合は: python3 scripts/build_gallery.py
"""

import os
import html

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg")

CATEGORIES = [
    {"key": "stickers", "dir": "stickers", "label": "Stickers"},
    {"key": "icons", "dir": "icons", "label": "Icons"},
]


def list_images(folder):
    path = os.path.join(REPO_ROOT, folder)
    if not os.path.isdir(path):
        return []
    files = [
        f for f in os.listdir(path)
        if f.lower().endswith(IMAGE_EXTS) and not f.startswith(".")
    ]
    files.sort()
    return files


def title_from_filename(filename):
    name = os.path.splitext(filename)[0]
    name = name.replace("-", " ").replace("_", " ")
    return name.strip()


def render_card(folder, filename):
    src = f"../{folder}/{filename}"
    title = html.escape(title_from_filename(filename))
    esc_name = html.escape(filename)
    return f"""
    <figure class="card">
      <img src="{src}" alt="{title}" loading="lazy" />
      <figcaption>
        <span class="name">{title}</span>
        <code class="path">{folder}/{esc_name}</code>
      </figcaption>
    </figure>"""


def render_section(cat):
    files = list_images(cat["dir"])
    cards = "".join(render_card(cat["dir"], f) for f in files) if files else \
        '<p class="empty">まだ画像がありません。' \
        f'<code>{cat["dir"]}/</code> フォルダに画像を追加してください。</p>'
    return f"""
  <section id="{cat['key']}">
    <h2>{cat['label']} <span class="count">({len(files)})</span></h2>
    <div class="grid">{cards}
    </div>
  </section>"""


def build():
    sections = "".join(render_section(c) for c in CATEGORIES)
    total = sum(len(list_images(c["dir"])) for c in CATEGORIES)

    html_out = f"""<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>天汐香弓 Asset Gallery</title>
<style>
  :root {{
    --bg: #fdf6fb;
    --card-bg: #ffffff;
    --accent: #ff7ab8;
    --accent2: #7aa8ff;
    --text: #3a2e3f;
    --muted: #8a7d8f;
    --border: #f0dcee;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    font-family: "Hiragino Sans", "Yu Gothic UI", system-ui, sans-serif;
    background: var(--bg);
    color: var(--text);
  }}
  header {{
    padding: 40px 24px 20px;
    text-align: center;
  }}
  header h1 {{
    margin: 0 0 6px;
    font-size: 1.8rem;
    background: linear-gradient(90deg, var(--accent), var(--accent2));
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }}
  header p {{
    margin: 0;
    color: var(--muted);
    font-size: 0.9rem;
  }}
  nav {{
    display: flex;
    justify-content: center;
    gap: 12px;
    margin-top: 16px;
    flex-wrap: wrap;
  }}
  nav a {{
    padding: 6px 16px;
    border-radius: 999px;
    background: var(--card-bg);
    border: 1px solid var(--border);
    color: var(--text);
    text-decoration: none;
    font-size: 0.85rem;
  }}
  section {{
    max-width: 1100px;
    margin: 0 auto;
    padding: 24px;
  }}
  section h2 {{
    font-size: 1.2rem;
    border-left: 5px solid var(--accent);
    padding-left: 10px;
  }}
  .count {{ color: var(--muted); font-weight: normal; font-size: 0.9rem; }}
  .grid {{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: 18px;
    margin-top: 16px;
  }}
  .card {{
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 14px;
    margin: 0;
    text-align: center;
    box-shadow: 0 2px 10px rgba(0,0,0,0.03);
  }}
  .card img {{
    max-width: 100%;
    max-height: 140px;
    object-fit: contain;
  }}
  .card figcaption {{
    margin-top: 10px;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }}
  .card .name {{
    font-size: 0.85rem;
  }}
  .card .path {{
    font-size: 0.7rem;
    color: var(--muted);
    background: var(--bg);
    border-radius: 6px;
    padding: 2px 6px;
    word-break: break-all;
  }}
  .empty {{
    color: var(--muted);
    font-size: 0.9rem;
  }}
  footer {{
    text-align: center;
    padding: 30px;
    color: var(--muted);
    font-size: 0.75rem;
  }}
</style>
</head>
<body>
<header>
  <h1>Asset Gallery</h1>
  <p>全 {total} 点 ／ stickers・icons フォルダに画像を追加すると自動で反映されます</p>
  <nav>
    {"".join(f'<a href="#{c["key"]}">{c["label"]}</a>' for c in CATEGORIES)}
  </nav>
</header>
{sections}
<footer>Auto-generated by scripts/build_gallery.py — do not edit this file by hand.</footer>
</body>
</html>
"""

    out_dir = os.path.join(REPO_ROOT, "docs")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "index.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"Wrote {out_path} ({total} images)")


if __name__ == "__main__":
    build()
